// SPDX-FileCopyrightText: Iridesium
// SPDX-License-Identifier: GPL-3.0-only

//! The backend-agnostic scripting interface.
//!
//! Everything here is deliberately free of any backend's types. If a signature
//! in this file mentions `mlua`, the abstraction has failed.

use std::path::Path;

use crate::chunk::Chunk;
use crate::coords::{BlockPos, ChunkPos, SubNodePos};
use crate::material::MaterialId;

/// Which scripting backend a build was compiled against.
///
/// Reported by `server --version` and written into the world's meta, because a
/// world generated by mods running on one dialect is not guaranteed to
/// regenerate identically on another.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Backend {
    /// Lua 5.4 — the reference implementation. Integer subtype, current
    /// semantics.
    Lua54,
    /// `LuaJIT` — Lua 5.1 semantics, tracing JIT.
    LuaJit,
    /// Luau — Roblox's Lua 5.1 derivative, built for untrusted code.
    Luau,
}

impl Backend {
    /// The dialect mods are written against.
    ///
    /// **This string goes in the modding documentation and cannot change**
    /// without invalidating every mod ever written against it.
    #[must_use]
    pub const fn dialect(self) -> &'static str {
        match self {
            Self::Lua54 => "Lua 5.4",
            Self::LuaJit | Self::Luau => "Lua 5.1",
        }
    }

    /// Whether this backend has an integer subtype.
    ///
    /// The single most mod-visible difference between the candidates. Under
    /// 5.1 semantics every number is a double, so `1/2` is `0.5` and there is
    /// no `//` operator — code written for one dialect misbehaves subtly on the
    /// other rather than failing loudly.
    #[must_use]
    pub const fn has_integers(self) -> bool {
        matches!(self, Self::Lua54)
    }

    /// Whether this backend can bound a runaway loop.
    ///
    /// **`LuaJIT` cannot.** The budget is a debug hook, and `LuaJIT`'s debug hook
    /// does not fire inside JIT-compiled traces — a hot loop compiles, leaves
    /// the interpreter, and never returns to be counted. `while true do end` in
    /// a mod runs forever.
    ///
    /// Charter rule 10 requires a mod error to disable that mod and never kill
    /// the tick, so this is a containment failure rather than a performance
    /// nuance. Recorded here as a property of the backend so it is discoverable
    /// from the code, not only from `docs/scripting-vm.md` §5.
    #[must_use]
    pub const fn can_bound_runaway_loops(self) -> bool {
        !matches!(self, Self::LuaJit)
    }

    /// Whether this backend can enforce a memory ceiling.
    ///
    /// **`LuaJIT` cannot** — its allocator is tied to its own GC and `mlua`
    /// cannot install a limit.
    #[must_use]
    pub const fn can_bound_memory(self) -> bool {
        !matches!(self, Self::LuaJit)
    }

    /// Whether this backend can contain untrusted third-party mods.
    ///
    /// Both containment primitives are required. A backend missing either one
    /// may be built for benchmarking but must not be the shipped default.
    #[must_use]
    pub const fn can_contain_untrusted_mods(self) -> bool {
        self.can_bound_runaway_loops() && self.can_bound_memory()
    }

    /// Short name for logs and documentation.
    #[must_use]
    pub const fn name(self) -> &'static str {
        match self {
            Self::Lua54 => "lua54",
            Self::LuaJit => "luajit",
            Self::Luau => "luau",
        }
    }
}

/// Resource limits applied to a script VM.
///
/// Both limits exist for the same reason: charter rule 10 requires a mod error
/// to disable that mod, never to kill the tick. A mod that loops forever or
/// allocates forever is a mod error, not a server outage.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct VmLimits {
    /// Ceiling on total VM allocation, in bytes.
    pub memory_bytes: usize,
    /// Ceiling on VM instructions executed inside one callback invocation.
    ///
    /// Per *invocation*, not per tick: a budget shared across a tick would make
    /// one mod's cost depend on how many other mods ran first, and a mod that
    /// worked alone would fail once a server installed something else.
    pub instructions_per_call: u32,
}

impl Default for VmLimits {
    fn default() -> Self {
        Self {
            // Generous: a mod holding a large lookup table is legitimate. This
            // is a runaway guard, not a diet.
            memory_bytes: 256 * 1024 * 1024,
            // Roughly a few milliseconds of interpreted Lua. Enough for real
            // orchestration, far short of a tick.
            instructions_per_call: 20_000_000,
        }
    }
}

/// Something went wrong in, or around, a script.
#[derive(Debug, thiserror::Error)]
pub enum ScriptError {
    /// The VM itself could not be created or configured.
    #[error("could not initialise the {backend} script VM")]
    Vm {
        /// Which backend.
        backend: &'static str,
        /// Underlying detail.
        detail: String,
    },

    /// A script failed to load or parse.
    #[error("mod `{mod_id}` failed to load")]
    Load {
        /// Which mod.
        mod_id: String,
        /// The backend's message, including a traceback where available.
        detail: String,
    },

    /// A script raised an error while running.
    ///
    /// Carries the mod id so the tick loop can attribute the fault and disable
    /// that mod without unwinding (charter rule 10).
    #[error("mod `{mod_id}` errored in {context}")]
    Runtime {
        /// Which mod.
        mod_id: String,
        /// What it was doing — the callback name, usually.
        context: String,
        /// The backend's message, including a traceback where available.
        detail: String,
    },

    /// A callback exceeded its instruction budget.
    #[error("mod `{mod_id}` exceeded its instruction budget in {context}")]
    BudgetExceeded {
        /// Which mod.
        mod_id: String,
        /// What it was doing.
        context: String,
    },

    /// A callback exceeded the VM memory limit.
    #[error("mod `{mod_id}` exceeded the script memory limit in {context}")]
    OutOfMemory {
        /// Which mod.
        mod_id: String,
        /// What it was doing.
        context: String,
    },

    /// A script tried to register something after the window closed.
    #[error("mod `{mod_id}` tried to register `{what}` after registration closed")]
    RegistrationClosed {
        /// Which mod.
        mod_id: String,
        /// What it tried to register.
        what: String,
    },
}

impl ScriptError {
    /// The mod to blame, if any.
    ///
    /// Every runtime failure has one, which is what makes "disable the mod, keep
    /// the server" possible.
    #[must_use]
    pub fn mod_id(&self) -> Option<&str> {
        match self {
            Self::Vm { .. } => None,
            Self::Load { mod_id, .. }
            | Self::Runtime { mod_id, .. }
            | Self::BudgetExceeded { mod_id, .. }
            | Self::OutOfMemory { mod_id, .. }
            | Self::RegistrationClosed { mod_id, .. } => Some(mod_id),
        }
    }
}

/// A texture a mod registered for one of its blocks.
///
/// The path is **relative to the mod's own directory** and stays that way all
/// the way to the content index. Resolving it against the filesystem here would
/// mean the engine handing a mod-supplied string to `std::fs`, which is exactly
/// the shape of a path-traversal bug; instead it is a key looked up in an index
/// built by walking that directory, so a path outside it simply does not match.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub struct BlockTexture {
    /// The qualified block id, e.g. `"core:white"`.
    pub block: String,
    /// The mod that registered it, which is also the directory the path is
    /// relative to.
    pub mod_id: String,
    /// Mod-relative path, forward-slashed.
    pub path: String,
}

pub use crate::dig::Brush;

/// What a mod said about how hard a block is to break, and what it yields.
///
/// Held apart from [`BlockTexture`] and [`ScriptVm::registered_blocks`] for the
/// same reason those are apart from each other: the id order is a contract with
/// the material registry, and widening that tuple would drag simulation rules
/// into it.
#[derive(Debug, Clone, PartialEq)]
pub struct BlockRules {
    /// The qualified block id.
    pub block: String,
    /// The sound a footstep on this block makes, if the mod named one.
    ///
    /// A qualified sound id. `None` means walking on it is silent, which is a
    /// legitimate answer and the one every block gets until a mod says
    /// otherwise — charter rule 1: the engine has no opinion about what stone
    /// sounds like.
    pub step_sound: Option<String>,
    /// Seconds to break with a bare hand.
    ///
    /// A default rather than an absence: every block has *some* hardness, and
    /// a mod that omits it gets [`BlockRules::DEFAULT_HARDNESS`] rather than an
    /// unbreakable block, because "I forgot to set hardness" should not produce
    /// bedrock.
    pub hardness: f32,
    /// How strongly this material imposes its hardness on a block it is only
    /// part of.
    ///
    /// `1.0` is neutral and what a mod that says nothing gets. Above it the
    /// material carries a mixture toward its own speed — which works in both
    /// directions, because the blend averages mining *rates*: a high dominance
    /// on something soft makes the whole block soft, and on something stubborn
    /// makes the whole block stubborn. See [`crate::dig::hardness`].
    pub dominance: f32,
    /// What breaking it yields, if the mod overrode the default.
    ///
    /// `None` means the ordinary rule from the Sub-Node Contract §9: the block
    /// drops itself, 27 units for a full block and one per occupied cell
    /// otherwise. `Some` replaces that outright, in units.
    pub drops: Option<Vec<(String, u32)>>,
    /// Light this block gives off, as `(r, g, b)` each 0..=15.
    ///
    /// `(0, 0, 0)` for almost everything — a block is not a lamp unless its mod
    /// says so. **The engine registers no light sources of its own**, the same
    /// way it registers no tools (charter rule 1): a world whose mods define no
    /// emissive block is a world lit only by the sky, and that is a mod set's
    /// decision rather than a missing engine feature.
    ///
    /// Sunlight is not settable here. It comes from the sky, not from a block.
    pub light_emit: (u8, u8, u8),
    /// How much fluid this block drinks per fluid tick, and what it becomes.
    ///
    /// `(0, None)` for anything that does not absorb, which is almost
    /// everything. The second half is a block id and is resolved against the
    /// registry by whoever holds one — charter rule 8 again.
    pub absorbs: (u32, Option<String>),
}

impl BlockRules {
    /// Seconds to break a block whose mod said nothing about hardness.
    pub const DEFAULT_HARDNESS: f32 = 0.75;

    /// How this block resists a tool, as the mixture blend wants it.
    #[must_use]
    pub const fn resistance(&self) -> crate::dig::Resistance {
        crate::dig::Resistance {
            hardness: self.hardness,
            dominance: self.dominance,
        }
    }

    /// What this block contributes to block light.
    ///
    /// The sun channel is always zero: a block emits colour, and daylight is
    /// the sky's business.
    #[must_use]
    pub const fn emission(&self) -> crate::light::Light {
        let (red, green, blue) = self.light_emit;
        crate::light::Light::new(0, red, green, blue)
    }
}

/// Somewhere a mod can change the world at runtime.
///
/// # The gap this fills
///
/// A mod could write terrain during worldgen and never again. Everything else
/// it might want to do to the world — a block that changes when fluid reaches
/// it, a crop that grows, a fire that spreads — was inexpressible, which made
/// the mod API smaller than the engine it is supposed to be the only API for
/// (charter rule 1).
///
/// # Blocks are named, not numbered
///
/// `block` is a string id, and that is not a convenience. Numeric ids come in
/// two flavours — the RUNTIME ids registration hands out and the WORLD ids the
/// database keeps — and charter rule 8 makes them different numbers. A mod
/// given the wrong one gets a comparison that works whenever the two coincide;
/// that exact bug reached a play session. Names have one meaning.
///
/// # Writes are queued, not applied
///
/// The implementation puts the edit on the same queue an operator's edits use
/// and the tick drains it. So a mod cannot write the world out from under the
/// system that is mid-tick reading it, and it needs no lock on the world to do
/// anything at all.
pub trait WorldEdit: Send + Sync {
    /// Replaces a whole block with `block`, or clears it if `block` is air.
    ///
    /// Returns whether the edit was accepted onto the queue — NOT whether it
    /// landed, which the caller finds out by looking next tick. `false` means
    /// the queue is full or the block name is not registered.
    fn set_block(&self, pos: crate::BlockPos, block: &str) -> bool;
}

/// What a mod said about a fluid.
///
/// Registered during the loading window and frozen with everything else
/// (charter rule 9). The engine keeps only what it must simulate and draw with;
/// how fast the fluid hurts, and what it sounds like landing on stone, are the
/// registering mod's business.
#[derive(Debug, Clone, PartialEq)]
pub struct FluidRules {
    /// The qualified fluid id, `"core:milk"`.
    pub fluid: String,
    /// The block material a full block of it is drawn as.
    ///
    /// A fluid has no material of its own in the block store — a block holds
    /// terrain and fluid independently — so this is what the mesher and the
    /// texture atlas look up. It names a registered block, which is what lets a
    /// mod give its fluid a texture without the engine growing a second,
    /// nearly-identical texture path.
    pub material: String,
    /// How full a block must be before this fluid treats it as floor, in cells
    /// of 27.
    ///
    /// Sub-Node Contract §4. Fourteen — over half — by default: under it a block
    /// is more air than anything and the fluid runs through, at or above it the
    /// block holds the fluid up. `1` is the old rule, where any chiselled cell
    /// at all made a block waterproof.
    pub waterlogs_at: u32,
    /// Simulation ticks between updates of this fluid.
    ///
    /// One means every fluid tick. Larger is slower and more viscous, and costs
    /// proportionally less to simulate — which is a real lever for a mod adding
    /// a fluid it expects to cover a lot of world.
    pub tick_rate: u8,
    /// One in how many fluid ticks an exposed block loses a cell, or zero.
    ///
    /// A declared sink (Sub-Node Contract §4.3), and zero — the default —
    /// never evaporates. Only a block open to the air above loses anything, so
    /// a wide shallow pool goes before a deep narrow one.
    pub evaporates: u32,
    /// What being inside it looks like, sRGB `0..=255`.
    pub color: [u8; 3],
}

impl FluidRules {
    /// How often a fluid updates if its mod said nothing.
    pub const DEFAULT_TICK_RATE: u8 = 1;

    /// How full a block must be to be floor, if its mod said nothing.
    pub const DEFAULT_WATERLOGS_AT: u32 = 14;

    /// Whether a fluid evaporates, if its mod said nothing. It does not.
    pub const DEFAULT_EVAPORATES: u32 = 0;

    /// What a fluid looks like from inside, if its mod said nothing.
    ///
    /// White, which is milk's own answer and a visible one for anything else —
    /// a mod that forgot the field gets a tint it will notice rather than a
    /// transparent one it will not.
    pub const DEFAULT_COLOR: [u8; 3] = [255, 255, 255];
}

/// How a moment's finished picture is graded.
///
/// Every field is an identity by default, so a keyframe that says nothing about
/// grading is graded not at all — which is what makes this additive rather than
/// a change to how existing skies look.
///
/// # What each one does, and in what order
///
/// `exposure` scales the scene BEFORE the highlight roll-off, so it decides how
/// much of the picture reaches the shoulder. The rest run afterwards, on the
/// finished display-referred image, in this order: contrast about a mid-grey
/// pivot, saturation towards luma, `tint` multiplying and `offset` adding, then
/// `gamma`. The order is fixed and the client's LUT bake is its only
/// implementation — see `client::render::grade`.
///
/// # Why so few knobs
///
/// A full grading stack is content-authoring machinery, and the engine's job is
/// to make a look expressible rather than to be a colourist. These six describe
/// "cooler and flatter at night, warm and contrasty at dusk" — which is what a
/// day cycle actually needs — and every one of them has an obvious identity.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct SkyGrade {
    /// Multiplies the scene before the tonemap. 1.0 is none.
    pub exposure: f32,
    /// Multiplies each channel of the graded image. `[1, 1, 1]` is none.
    pub tint: [f32; 3],
    /// Added to each channel after `tint`. `[0, 0, 0]` is none.
    pub offset: [f32; 3],
    /// Pushes each channel away from mid grey. 1.0 is none.
    pub contrast: f32,
    /// Blends towards luma at 0 and away from it above 1. 1.0 is none.
    pub saturation: f32,
    /// Applied last, per channel. 1.0 is none.
    pub gamma: f32,
}

impl SkyGrade {
    /// No grading at all: what a keyframe with no `grade` table gets.
    pub const NONE: Self = Self {
        exposure: 1.0,
        tint: [1.0; 3],
        offset: [0.0; 3],
        contrast: 1.0,
        saturation: 1.0,
        gamma: 1.0,
    };

    /// Whether this grade would leave the picture exactly as it found it.
    ///
    /// **The client skips the LUT entirely when this holds**, so an ungraded
    /// world is not merely close to what it was before grading existed but
    /// identical to it — an 8-bit LUT of the identity is not quite the identity,
    /// and Task 08's screenshot hashes are asserted on exact values.
    #[must_use]
    pub fn is_none(&self) -> bool {
        *self == Self::NONE
    }
}

impl Default for SkyGrade {
    fn default() -> Self {
        Self::NONE
    }
}

/// One moment in a mod's day, as a set of colours.
///
/// The sky is a list of these and the client interpolates between them, which
/// is why a mod can describe dawn without the engine knowing what dawn is.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct SkyKeyframe {
    /// When in the day, `0.0..=1.0`, where 0 is midnight and 0.5 is noon.
    pub time: f32,
    /// The sky's own colour, which is also what distance fog fades towards.
    pub sky: [f32; 3],
    /// The sun's colour, multiplied into the stored sunlight channel.
    pub sun: [f32; 3],
    /// How strong the sun is, `0.0..=1.0`.
    ///
    /// **This scales stored sunlight at draw time**, which is what makes a
    /// day/night cycle free: the world's sunlight is always full daylight, so
    /// dusk dirties no chunks and relights nothing.
    pub intensity: f32,
    /// How the finished picture is graded at this moment.
    ///
    /// Interpolated between keyframes like the colours are, and only lighting
    /// mode 3 applies it — grading is a property of the post chain, and modes 1
    /// and 2 have no post chain to put it in.
    pub grade: SkyGrade,
}

/// The sky a mod registered.
///
/// **Charter rule 1 in its purest form.** The engine has no opinion about how
/// long a day is, what colour the sky goes at dusk, or whether there is a day
/// at all — a world whose mods register no sky gets a fixed one and never
/// changes. Everything here is content.
#[derive(Debug, Clone, PartialEq)]
pub struct Sky {
    /// The mod that registered it.
    pub mod_id: String,
    /// Ticks in one full day.
    ///
    /// At the 20 Hz tick, 24,000 is twenty minutes — the figure this genre
    /// settled on, chosen here by the reference mod rather than by the engine.
    pub day_length_ticks: u32,
    /// Colour keyframes, sorted by time and never empty.
    pub keyframes: Vec<SkyKeyframe>,
    /// Where a fresh world's clock starts, `0.0..1.0`.
    ///
    /// **A world used to begin at midnight**, because that is where a counter
    /// starting at zero puts it, and the result was a first impression with no
    /// sun in it: no shadows, no colour, and every graphics setting looking
    /// identical because there was nothing lit to tell them apart. Which hour a
    /// world opens on is content — how long the day is and what colour it goes
    /// already are — so the mod says.
    pub start_time: f32,
}

/// A named action a mod registered.
///
/// Charter rule 11: a mod registers a NAME, the engine owns the key. This is
/// the whole of what a mod gets to say about controls — there is deliberately
/// no way to ask which key it ended up on, because a mod that could ask would
/// start branching on it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Action {
    /// The qualified action id, e.g. `"core_tools:chisel_mode"`.
    pub id: String,
    /// One line for the settings screen. Empty when the mod did not say.
    pub description: String,
    /// The mod that registered it, for attribution in the client's UI.
    pub mod_id: String,
    /// The binding the mod suggests, as a winit `KeyCode` name.
    ///
    /// A STRING, because `crates/core` must never depend on winit (charter
    /// rule 3). The client parses it and warns about one it does not know.
    /// Empty means the mod shipped it unbound.
    pub default_key: String,
}

/// A tool a mod registered.
#[derive(Debug, Clone, PartialEq)]
pub struct Tool {
    /// The qualified tool id, e.g. `"core_tools:chisel"`.
    pub id: String,
    /// What to call it on screen, if the mod said.
    ///
    /// `None` falls back to the id, which is always present and always
    /// unambiguous — an unnamed tool should look unpolished, not invisible.
    pub name: Option<String>,
    /// What shape it removes.
    pub brush: Brush,
    /// How much faster than a bare hand it digs.
    pub speed_multiplier: f32,
    /// Whether this is what a player digs with holding nothing.
    ///
    /// The engine has no bare hand of its own. It knows how to *count* a dig
    /// and nothing about what breaking things should feel like, so a world
    /// whose mods register no tools is a world nobody can dig in — which is
    /// the shape charter rule 1 asks for, and is verified by deleting `game/`
    /// in a test.
    ///
    /// Several mods may each mark one; the lowest id wins, so the result does
    /// not depend on load order.
    pub default: bool,
}

/// A dig the server is about to carry out.
///
/// Handed to `on_dig_complete` *before* the geometry goes, so a mod that
/// refuses it leaves the world untouched. Refusing after the fact would mean
/// putting the block back, and putting a block back is not the same as never
/// having removed it — the drops have already been computed and the removal has
/// already been broadcast.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DigEvent {
    /// Who is digging, as the canonical player UUID (charter rule 13 — never
    /// the display name). 32 bytes, because it is a BLAKE3 of the root key.
    pub player: [u8; 32],
    /// The cell under their crosshair.
    pub target: SubNodePos,
    /// What is there.
    pub material: MaterialId,
    /// What the tool would remove.
    pub brush: Brush,
}

/// A placement the server is about to carry out.
///
/// Handed to `on_place` after the engine's own rules have passed — the player
/// holds the material, the target is empty, nobody is standing in it — and
/// before anything is written or charged. A mod refusing here costs the player
/// nothing.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PlaceEvent {
    /// Who is placing.
    pub player: [u8; 32],
    /// The block that would be written.
    pub block: BlockPos,
    /// What it would be made of.
    pub material: MaterialId,
    /// Which of its 27 cells would be filled.
    pub occupancy: u32,
    /// How many units it would cost, which is `occupancy.count_ones()`.
    pub units: u32,
}

/// Somebody hitting something.
///
/// The attacker is a canonical player UUID (charter rule 13); the target is an
/// **entity**, because that is what everything in the world is now — including
/// the other players, who are mirrored into the entity store every tick.
///
/// This is the "wider target type" the Task 09 version of this struct said
/// entities would need. It arrived: a punch names an entity id, and a mod that
/// wants to know whether it hit a person reads that entity's `owner`.
///
/// # The engine has no opinion about what a hit does
///
/// Nothing in core reacts. Damage, knockback, aggro, or nothing at all are game
/// decisions and charter rule 1 puts them in mods — the engine's job is to say
/// who hit what, in a way a client cannot lie about.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PunchEvent {
    /// Who threw the punch.
    pub attacker: [u8; 32],
    /// The entity that took it.
    pub target: crate::ent::EntityId,
    /// The player that entity belongs to, if it belongs to one.
    ///
    /// Carried rather than left for the mod to look up, because the commonest
    /// question about a punch is "did somebody hit a person" and the answer is
    /// one field the engine already has in its hand.
    pub owner: Option<[u8; 32]>,
}

/// A player arriving in the world.
///
/// # Why the engine does not say whether this is their first time
///
/// It knows, and telling you would be content. "First-ever join" is a rule a
/// mod invents — a mob imprints on one, a tutorial greets one, a shop gives
/// one a starting stack — and every one of them wants a different definition of
/// first. `game.storage` is how a mod remembers what it has seen, so the fact
/// belongs there rather than in an engine field that would be right for exactly
/// one mod (charter rule 1).
///
/// The UUID is the identity and the name is a per-server claim bound to it
/// (charter rule 13). Both are here because a mod needs the first to remember
/// anything and the second to say anything.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct JoinEvent {
    /// Who arrived, canonically.
    pub player: [u8; 32],
    /// What they are currently called on this server.
    pub name: String,
}

/// One block the engine chose to offer a mod this tick.
///
/// **The mechanism behind everything that happens on its own**: a crop
/// growing, grass spreading onto bare earth, a sapling becoming a tree, leaves
/// decaying, fire going out, ice melting. None of those is a thing a player
/// did, and without this a mod could only make them happen to blocks it had
/// remembered itself — which leaves out every block worldgen made.
///
/// **Only for materials a mod asked about.** The engine picks cells at random
/// and looks at what is in them; a Lua call happens only when the material has
/// a handler. Otherwise a busy world would spend its tick calling into a script
/// about stone.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RandomTickEvent {
    /// The block, in world blocks.
    pub pos: crate::coords::BlockPos,
    /// What is in it, as a RUNTIME id — the number `game.get_block_id` hands
    /// out, which is what a mod can compare against (charter rule 8).
    pub material: crate::MaterialId,
}

/// A player has gone.
///
/// **The other half of a join, and a mod needs both.** Anything a mod keeps per
/// player — a party, a claim, a timer, a bar it was drawing — is bookkeeping it
/// can start on a join and could never end. `game.storage` persists across a
/// session either way; what this is for is everything that should NOT.
///
/// Fired from the tick that noticed, after any container they had open has been
/// put back and **before their inventory is written**, so a mod that wants to
/// drop what they were carrying can still read and empty it.
///
/// It fires for a disconnection the server never saw coming as well as a clean
/// one: the tick compares who is present against who was, so a dropped
/// connection is the same event as a goodbye.
///
/// **Somebody who arrives and goes inside one tick produces neither event.**
/// Both halves are the same diff, so the two are missed together rather than a
/// mod being told about a departure it never heard the arrival of.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LeaveEvent {
    /// Who left, canonically (charter rule 13).
    pub player: [u8; 32],
    /// What they were called on this server.
    pub name: String,
}

/// A player pressed or released an action their server's mod registered.
///
/// **An observation, not a veto.** The player pressed a key; nothing a mod says
/// can un-press it. The outcome exists only so a misbehaving mod is disabled
/// the way it is everywhere else (charter rule 10).
///
/// Charter rule 11 in one struct: the mod is told WHAT was done, never which
/// key did it. There is no field here for a key and there is not going to be.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ActionEvent {
    /// Who did it, canonically — the UUID, never the display name (rule 13).
    pub player: [u8; 32],
    /// The qualified action id, e.g. `"core_tools:chisel_mode"`.
    pub id: String,
    /// Whether it went down (`true`) or came up (`false`).
    pub pressed: bool,
}

/// A line a player typed.
///
/// # Why chat is engine-native and still hookable
///
/// Chat is in the engine because moderation and RCON depend on it: a server
/// operator must be able to read and stop what is said without every server
/// having installed the same mod. Mods still get a veto, because "what may be
/// said here" is policy and policy is content (charter rule 1).
#[derive(Debug, Clone, PartialEq)]
pub struct ChatEvent {
    /// Who said it, canonically — the UUID, never the display name (rule 13).
    pub player: [u8; 32],
    /// What they typed.
    pub text: String,
}

/// Something a player did inside a dialog a mod opened.
///
/// # Why this carries the owning mod
///
/// A dialog belongs to whoever opened it, and only that mod is told about its
/// events. Anything else would let one mod watch what a player typed into
/// another's text field, or act on a button it did not put there. The server
/// records the owner when the dialog opens and routes on it here.
#[derive(Debug, Clone, PartialEq)]
pub struct DialogEvent {
    /// Who did it, canonically — the UUID, never the display name (rule 13).
    pub player: [u8; 32],
    /// The mod that owns the dialog, and the only one told.
    pub mod_id: String,
    /// The qualified form name, e.g. `"core_ui:inventory"`.
    pub form: String,
    /// What happened.
    pub event: crate::proto::DialogEvent,
}

/// Fluid pressing against something it cannot get into.
///
/// # Why the hook is about the flow that DIDN'T happen
///
/// Where a fluid went is already in the world — a mod can read it back with
/// `game.get_fluid`. Where it *tried* to go is not recorded anywhere by
/// definition: a block milk cannot enter is a block with no milk in it, and it
/// looks exactly like a block milk never reached.
///
/// That is the fact a waterlogging mod needs, and it is why this event carries
/// what is in the way as well as where. See `game/core_milk` for the reference
/// implementation, and the Sub-Node Contract §4 for what "cannot get into"
/// means at sub-node resolution.
///
/// **Budgeted at the solver**, so a shoreline a thousand blocks long reports a
/// bounded sample per tick rather than handing the script VM the whole coast.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FluidFlowEvent {
    /// The block the fluid is in.
    pub from: BlockPos,
    /// The block it could not enter.
    pub into: BlockPos,
    /// Which fluid, by its registered string id.
    pub fluid: String,
    /// How much it is pressing with, in cells of 27.
    pub volume: u32,
    /// The material of the block in the way.
    ///
    /// A **runtime** id, resolved to its string before it reaches Lua — charter
    /// rule 8 again: a numeric id handed to a mod is a number that means
    /// something different on the next run.
    pub blocked_by: MaterialId,
    /// Which of the blocking block's 27 cells are filled.
    ///
    /// The whole mask rather than a count, because "how much" and "which shape"
    /// are different questions and only one of them can be recovered from a
    /// count. A mod deciding whether to swap in a waterlogged block wants the
    /// count; a mod carving a channel wants the shape.
    pub occupancy: u32,
}

/// What a round of cancellable hooks decided.
///
/// # A faulted mod does not get a veto
///
/// Charter rule 10 says a mod error disables that mod and never kills the tick.
/// The corollary here is that an error is **not** a refusal: a mod that throws
/// while deciding whether a dig may proceed is disabled and the dig goes ahead.
/// The alternative — treating a crash as "no" — would let one broken mod stop
/// everybody on the server from digging, which is a far worse failure than the
/// one it was trying to prevent.
#[derive(Debug, Default)]
pub struct HookOutcome {
    /// Whether the action may proceed.
    pub allowed: bool,
    /// What to tell the player, when the mod said.
    ///
    /// # Cancelling has two meanings and the engine could not tell them apart
    ///
    /// A hook returning `false` means "this does not happen", and that covers
    /// two quite different intentions: *refusing* the player, and *handling*
    /// the action itself. `core_milk` is the second — it pours milk and cancels
    /// the block write, because the block was only ever a way of naming what to
    /// pour — and it was being answered with "you cannot build there" every time
    /// it worked. Reported from the window, with a log showing the pour
    /// succeeding on the line above the complaint.
    ///
    /// So the return value now says which:
    ///
    /// | returned | meaning |
    /// |---|---|
    /// | nothing, or anything truthy | allowed |
    /// | `false` | refused; the caller's own wording is shown |
    /// | a non-empty string | refused; that wording is shown |
    /// | `""` | cancelled, and the player is told nothing |
    ///
    /// `None` here is the `false` case. Use [`HookOutcome::notice`] rather than
    /// reading it directly, so every caller spells the ladder the same way.
    pub reason: Option<String>,
    /// Mods that faulted during this round, now disabled.
    pub faults: Vec<(String, ScriptError)>,
}

/// The longest refusal a mod may put in front of a player.
///
/// A mod is not hostile, but it can be buggy, and this ends up on the wire —
/// [`crate::proto::MAX_CHAT_BYTES`] is the cap a chat message gets and there is
/// no reason a refusal should get more.
pub const MAX_REFUSAL_BYTES: usize = crate::proto::MAX_CHAT_BYTES;

impl HookOutcome {
    /// An outcome nothing objected to.
    #[must_use]
    pub const fn allow() -> Self {
        Self {
            allowed: true,
            reason: None,
            faults: Vec::new(),
        }
    }

    /// What to say to the player, given the caller's own default wording.
    ///
    /// `None` for "say nothing": either the action was allowed, or a mod
    /// cancelled it silently because it had handled the action itself.
    #[must_use]
    pub fn notice<'a>(&'a self, default: &'a str) -> Option<&'a str> {
        if self.allowed {
            return None;
        }
        match self.reason.as_deref() {
            // A mod that cancelled without saying anything gets the caller's
            // wording, because a refusal nobody explains reads as the game
            // being broken.
            None => Some(default),
            Some("") => None,
            Some(reason) => Some(reason),
        }
    }
}

/// A script VM hosting the server-mod tier.
///
/// Implementors own the sandbox. Nothing above this trait may assume a
/// particular language, let alone a particular implementation of one.
pub trait ScriptVm: Sized {
    /// Which backend this is.
    fn backend() -> Backend;

    /// Creates a VM with the given limits, with the registration window **open**.
    ///
    /// # Errors
    ///
    /// [`ScriptError::Vm`] if the VM cannot be created or the sandbox cannot be
    /// installed.
    fn create(limits: VmLimits) -> Result<Self, ScriptError>;

    /// Loads a mod's entry chunk into a fresh sandboxed environment.
    ///
    /// `dir` bounds what the mod's `require` can reach. Runs during the
    /// registration window.
    ///
    /// # Errors
    ///
    /// [`ScriptError::Load`] or [`ScriptError::Runtime`] if the chunk fails to
    /// compile or errors while running.
    fn load_mod(&mut self, mod_id: &str, source: &str, dir: &Path) -> Result<(), ScriptError>;

    /// Closes the registration window and freezes the registries.
    ///
    /// Charter rule 9's lifecycle: after this, `register_*` is a hard error.
    ///
    /// # Errors
    ///
    /// [`ScriptError::Vm`] if the VM state cannot be updated.
    fn freeze(&mut self) -> Result<(), ScriptError>;

    /// Whether the registration window has been closed.
    fn is_frozen(&self) -> bool;

    /// Points `game.get_light` at the world's light.
    ///
    /// Called once, after the world exists and therefore after freeze. Until it
    /// is, `game.get_light` answers darkness rather than failing: a mod reading
    /// light during worldgen — before there is any — should not have to know
    /// the engine's startup order.
    fn set_light_source(&mut self, source: std::sync::Arc<dyn crate::light::LightSource>);

    /// Points `game.set_block` at the world.
    ///
    /// Called once, after the world exists. Until then writes are dropped, the
    /// same way fluid reads answer empty — a mod calling this during worldgen is
    /// early rather than wrong, and `register_on_generate` is where terrain
    /// belongs at that point anyway.
    fn set_world_edit(&mut self, edit: std::sync::Arc<dyn crate::script::WorldEdit>);

    /// Points `game.get_fluid` and `game.set_fluid` at the world's fluid.
    ///
    /// Called once, after the world exists. Until then both answer as though
    /// there is no fluid anywhere, which is true — see [`crate::fluid::Access`].
    fn set_fluid_access(&mut self, access: std::sync::Arc<dyn crate::fluid::Access>);

    /// Points `game.get_tool` and `game.set_tool` at the connected players.
    ///
    /// Called once, after the server exists. Until then `get_tool` answers a
    /// bare hand and `set_tool` is dropped — a mod calling either during
    /// worldgen is early rather than wrong, since there is nobody holding
    /// anything yet.
    fn set_tools_access(&mut self, access: std::sync::Arc<dyn crate::dig::Tools>);

    /// Points `game.inventory`, `game.give` and `game.take` at the players.
    ///
    /// The same seam as [`Self::set_tools_access`], for the same reason: the
    /// frozen API is installed before there is anybody carrying anything, and
    /// crafting is a mod's job (charter rule 1) so a mod has to be able to
    /// spend material and hand something back.
    fn set_inventory_access(&mut self, access: std::sync::Arc<dyn crate::inventory::Access>);

    /// Points `game.play_sound` at the connected players.
    ///
    /// Called once, after the server exists. Until then a request is dropped —
    /// a mod making a noise during worldgen has nobody to make it for.
    fn set_sound_access(&mut self, access: std::sync::Arc<dyn crate::sound::Access>);

    /// Points `game.show_dialog` and friends at the connected players.
    ///
    /// The same seam as [`Self::set_sound_access`], for the same reason: the
    /// API is installed before there is anybody to show a dialog to, and a mod
    /// opening one during worldgen has no screen to open it on.
    fn set_dialog_access(&mut self, access: std::sync::Arc<dyn crate::ui::host::Access>);

    /// Points the entity API at the server's store.
    ///
    /// The same seam as [`Self::set_fluid_access`], for the same reason: the
    /// frozen API is installed before there is a world to have entities in.
    fn set_entity_access(&mut self, access: std::sync::Arc<dyn crate::ent::Access>);

    /// Points `game.storage` at the server's store.
    fn set_storage_access(&mut self, access: std::sync::Arc<dyn crate::storage::Access>);

    /// Points the container API at the world's containers.
    fn set_container_access(&mut self, access: std::sync::Arc<dyn crate::inventory::Containers>);

    /// Points `game.set_hud` at the per-player HUD values.
    ///
    /// The same seam as the others, and the reason it is one: the engine has
    /// no health bar and should not (charter rule 1), so the only way a mod's
    /// numbers reach a mod's own HUD script is a channel the engine carries
    /// and does not read.
    fn set_hud_access(&mut self, access: std::sync::Arc<dyn crate::hud::Access>);

    /// Points `game.line_of_sight` at the world.
    ///
    /// **Unlike every other setter here, what is behind this handle appears and
    /// disappears within a tick.** The world is not a store the server can hand
    /// over once: the tick thread owns it and holds it mutably through chunk
    /// generation and every edit, so it is lent out for the part of the tick
    /// that runs mod callbacks and taken back afterwards. A mod that reads it
    /// outside that window is told so — see [`crate::sight::Access`].
    fn set_sight_access(&mut self, access: std::sync::Arc<dyn crate::sight::Access>);

    /// Points `game.find_path` at the world.
    ///
    /// The same lending window as [`Self::set_sight_access`], because it is the
    /// same world and the same moment — see [`crate::path::Access`]. Two
    /// setters rather than one because sight and navigation are two questions,
    /// and a mod that only ever asks one of them should not have to know the
    /// other exists.
    fn set_path_access(&mut self, access: std::sync::Arc<dyn crate::path::Access>);

    /// Runs every registered `on_generate` callback for one chunk.
    ///
    /// # Errors
    ///
    /// [`ScriptError`] naming the mod that failed. A failure here disables that
    /// mod; it does not stop generation for the others.
    fn generate_chunk(
        &mut self,
        world_seed: u64,
        pos: ChunkPos,
        fill: MaterialId,
    ) -> Result<Chunk, ScriptError>;

    /// Runs every registered `on_tick` callback once.
    ///
    /// `dt_ticks` is how many simulation steps this call covers — normally 1,
    /// but more when the server has fallen behind and is catching up. Mods get
    /// a count of steps rather than a duration on purpose: a duration would
    /// tempt a mod to scale behaviour by wall-clock time, and two servers
    /// running at different speeds would then produce different worlds.
    ///
    /// **A failing mod is disabled, not fatal** (charter rule 10). This runs
    /// every non-faulted mod even if an earlier one errored, and reports the
    /// failures afterwards, because stopping at the first would let one bad mod
    /// silently starve every mod registered after it.
    ///
    /// # Errors
    ///
    /// Never returns `Err` for a mod fault — those are in the returned list.
    /// The `Result` is for a VM-level failure that affects everything.
    fn tick(&mut self, dt_ticks: u32) -> Result<Vec<(String, ScriptError)>, ScriptError>;

    /// Runs one mod's per-entity step callback over the entities it owns.
    ///
    /// Called once per tick per mod, with the ids of every live entity whose
    /// `source` is that mod. The engine does the grouping because it is the
    /// only side that knows which entity belongs to whom — a mod asking would
    /// have to be trusted with the answer.
    ///
    /// Each entity costs its own instruction budget, not a share of one. A mod
    /// with two hundred mobs must not get a two-hundredth of a budget each,
    /// and one runaway mob must not starve the other hundred and ninety-nine.
    ///
    /// # Errors
    ///
    /// [`ScriptError`] if the VM itself failed. A callback that raised is
    /// reported in the returned list and its mod is disabled (charter rule 10),
    /// exactly as [`Self::tick`] does.
    fn entity_step(
        &mut self,
        mod_id: &str,
        entities: &[u64],
        dt_ticks: u32,
    ) -> Result<Option<(String, ScriptError)>, ScriptError>;

    /// Which mods registered a per-entity step callback, in load order.
    fn entity_steppers(&self) -> Vec<String>;

    /// Asks every registered `on_dig_complete` whether a dig may proceed.
    ///
    /// Called **before** the geometry is removed. A mod returning `false`
    /// cancels it; returning nothing, `nil`, or anything else allows it, so a
    /// hook that only wants to observe does not have to remember to return
    /// anything.
    ///
    /// **Stops at the first refusal.** Once a dig is not happening, running the
    /// remaining hooks would invite them to take side effects — spawn an
    /// effect, charge something, log a break — for an action that will not
    /// occur. The cost is that a later mod does not observe an attempt an
    /// earlier one vetoed, which is the lesser problem and is deterministic:
    /// hook order is load order, which the resolver already fixed.
    fn dig_complete(&mut self, event: &DigEvent) -> HookOutcome;

    /// Asks every registered `on_place` whether a placement may proceed.
    ///
    /// The same rules as [`Self::dig_complete`], and called after the engine's
    /// own checks pass but before anything is written or charged.
    fn place(&mut self, event: &PlaceEvent) -> HookOutcome;

    /// Tells every registered `on_player_join` that somebody arrived.
    ///
    /// Nothing is being asked — they are already in the world — so the outcome
    /// carries only the faults, exactly as `fluid_flow` does. Refusing entry is
    /// not a mod's decision to make here: an allowlist is charter rule 13's
    /// business and happens long before a body exists.
    fn player_join(&mut self, event: &JoinEvent) -> HookOutcome;

    /// Runs every `on_player_leave` hook.
    fn player_leave(&mut self, event: &LeaveEvent) -> HookOutcome;

    /// Runs the handler for one randomly-chosen block.
    ///
    /// Called only for a material some mod registered — see
    /// [`ScriptVm::random_tick_materials`].
    fn random_tick(&mut self, event: &RandomTickEvent) -> HookOutcome;

    /// Which materials have a random-tick handler, after the freeze.
    ///
    /// **Asked once and kept**, because the alternative is a call into the VM
    /// for every cell the engine samples — thousands a tick, almost all of them
    /// stone.
    fn random_tick_materials(&self) -> Vec<MaterialId>;

    /// Asks every registered `on_punch` whether a hit lands.
    ///
    /// The same rules again. A mod returning `false` means the hit did not
    /// land, and no later hook is asked — the same first-refusal-wins rule
    /// [`Self::dig_complete`] documents, and for the same reason.
    fn punch(&mut self, event: &PunchEvent) -> HookOutcome;

    /// Tells every registered `on_action` that a player used one.
    ///
    /// **An observation, not a veto**, like [`Self::fluid_flow`]: the key is
    /// already down. The outcome carries only whether the mod errored, which is
    /// what disables it.
    fn action(&mut self, event: &ActionEvent) -> HookOutcome;

    /// Tells the OWNING mod that something happened in its dialog.
    ///
    /// **Only the owner**, unlike every other hook here, which tells everyone
    /// who registered. A dialog's events are private to the mod that opened it
    /// — see [`DialogEvent`].
    ///
    /// An observation rather than a veto: the player has already clicked. What
    /// the click MEANS — whether a stack moves — is the server's decision, made
    /// after this and against its own inventory.
    fn dialog_event(&mut self, event: &DialogEvent) -> HookOutcome;

    /// Asks every registered `on_chat` whether a line may be said.
    ///
    /// **A veto, unlike most hooks here.** A mod returning `false` stops the
    /// line reaching anybody, which is what makes a chat filter expressible —
    /// and the first refusal wins, so a later mod is not invited to act on a
    /// message that is not going to be sent.
    fn chat(&mut self, event: &ChatEvent) -> HookOutcome;

    /// Tells every registered `on_fluid_flow` that a flow was blocked.
    ///
    /// **An observation, not a veto.** The flow has already failed to happen and
    /// nothing a mod says can change that, so the returned outcome carries only
    /// the faults — a mod that throws in here is disabled like any other
    /// (charter rule 10) and the `allowed` field means nothing.
    ///
    /// What a mod does with it is act on the world, which is what
    /// `game.set_block` and `game.set_fluid` are for.
    fn fluid_flow(&mut self, event: &FluidFlowEvent) -> HookOutcome;

    /// Blocks registered during the loading window, **ordered by numeric id**.
    ///
    /// The order is the contract, not a convenience. The host replays these
    /// into [`crate::material::Registry`], which assigns ids sequentially, so
    /// replaying them in any other order would give a block a different id than
    /// the one the VM handed its mod — and every block that mod placed would
    /// silently be the wrong material.
    fn registered_blocks(&self) -> Vec<(String, MaterialId)>;

    /// Textures registered alongside blocks, ordered by block id.
    ///
    /// Separate from [`Self::registered_blocks`] on purpose: that method's
    /// order is a hard contract with the material registry, and widening its
    /// tuple would put a presentation concern in the middle of it. A block with
    /// no texture simply has no entry here — the engine has no opinion about
    /// what an untextured block looks like, and the client's placeholder is the
    /// client's business.
    fn registered_block_textures(&self) -> Vec<BlockTexture>;

    /// Breaking rules registered alongside blocks, ordered by block id.
    ///
    /// Every registered block appears, including those whose mod said nothing:
    /// the defaults are the engine's answer, and making a caller distinguish
    /// "no entry" from "default entry" is how one of them ends up unbreakable.
    fn registered_block_rules(&self) -> Vec<BlockRules>;

    /// Fluids registered during the loading window, ordered by fluid id.
    ///
    /// Empty for a mod set that registers none, which is most of them and is
    /// not a failure: a world with no fluid simply has no fluid, and the engine
    /// ships none of its own (charter rule 1).
    fn registered_fluids(&self) -> Vec<FluidRules>;

    /// Tools registered during the loading window, ordered by id.
    fn registered_tools(&self) -> Vec<Tool>;

    /// Ids registered as ITEMS rather than blocks, sorted.
    ///
    /// **The only thing that makes an item an item.** Everything a player can
    /// carry shares one id space (see `register_item` for why), and this is the
    /// list of the ones that may not be placed in the world.
    fn registered_items(&self) -> Vec<String>;

    /// Inventory views mods asked for, ordered by id.
    ///
    /// **Not `player:main`**, which every player has and no mod may resize —
    /// these are the extra places a mod wants stacks to be able to sit, like an
    /// armour rack or a tool belt. What the slots MEAN is the mod's; the engine
    /// gives them a name and a size and moves stacks between them.
    fn registered_views(&self) -> Vec<crate::inventory::ViewDef>;

    /// Every sound the loaded mods registered, in load order.
    fn registered_sounds(&self) -> Vec<crate::sound::Sound>;

    /// Every cue binding the loaded mods declared, in load order.
    ///
    /// Load order is precedence: two mods binding the same cue leave the later
    /// one holding it, which is how the rest of the mod system resolves a
    /// conflict. Empty is a mod set that makes no noise for any event, which is
    /// every mod set before this existed.
    fn registered_bindings(&self) -> Vec<crate::sound::Binding>;

    /// Every HUD script the loaded mods registered, in load order.
    ///
    /// Load order is DRAW order on the client, so this is a sequence rather
    /// than a map: a mod loaded later draws over one loaded earlier, which is
    /// the same rule the rest of the mod system uses to resolve a conflict.
    ///
    /// Empty is the ordinary case — a mod set that draws no HUD of its own, and
    /// a client that then shows the engine's crosshair and nothing more.
    fn registered_hud_scripts(&self) -> Vec<crate::hud::ScriptFile>;

    /// Every action the loaded mods registered, in load order.
    ///
    /// Load order rather than sorted, because that is the order the settings
    /// screen groups mods in and it is the only order a player can predict.
    fn registered_actions(&self) -> Vec<Action>;

    /// The sky a mod registered, if any.
    ///
    /// `None` means no mod registered one, which is a legitimate world rather
    /// than a failure: it simply has no day. Where several mods register one,
    /// the lowest mod id wins, for the same reason the default tool does —
    /// a rule that is arbitrary but fixed beats one that depends on load order.
    fn registered_sky(&self) -> Option<Sky>;

    /// Calls a named zero-argument global, for benchmarking and tests.
    ///
    /// # Errors
    ///
    /// [`ScriptError::Runtime`] if the call fails.
    fn call_void(&mut self, mod_id: &str, name: &str) -> Result<(), ScriptError>;

    /// Evaluates a chunk of source in a mod's environment and returns whether
    /// it succeeded. Test and diagnostic use.
    ///
    /// # Errors
    ///
    /// [`ScriptError`] if the source fails to compile or errors.
    fn eval_in(&mut self, mod_id: &str, source: &str) -> Result<(), ScriptError>;

    /// Mods currently marked faulted, in a stable order.
    ///
    /// A faulted mod's callbacks are skipped. Charter rule 10: a mod error
    /// disables that mod, never the tick.
    fn faulted_mods(&self) -> Vec<String>;

    /// Marks a mod faulted.
    fn mark_faulted(&mut self, mod_id: &str);
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_dialect_string_is_backend_specific() {
        // This string ends up in the modding docs. If it ever changes, every
        // mod written against the old one is at risk.
        assert_eq!(Backend::Lua54.dialect(), "Lua 5.4");
        assert_eq!(Backend::LuaJit.dialect(), "Lua 5.1");
        assert_eq!(Backend::Luau.dialect(), "Lua 5.1");
    }

    #[test]
    fn only_lua54_has_an_integer_subtype() {
        // The most mod-visible difference: under 5.1, `1/2` is 0.5 and there is
        // no `//`. Code silently misbehaves rather than failing loudly.
        assert!(Backend::Lua54.has_integers());
        assert!(!Backend::LuaJit.has_integers());
        assert!(!Backend::Luau.has_integers());
    }

    #[test]
    fn luajit_cannot_contain_untrusted_mods() {
        // Measured, not assumed: the sandbox suite hangs under vm-luajit
        // because the instruction budget never fires inside a compiled trace.
        // See docs/scripting-vm.md §5.
        assert!(!Backend::LuaJit.can_bound_runaway_loops());
        assert!(!Backend::LuaJit.can_bound_memory());
        assert!(!Backend::LuaJit.can_contain_untrusted_mods());

        // The two that can.
        for backend in [Backend::Lua54, Backend::Luau] {
            assert!(
                backend.can_contain_untrusted_mods(),
                "{backend:?} should be able to contain untrusted mods"
            );
        }
    }

    #[test]
    fn every_runtime_error_names_a_mod_to_blame() {
        // What makes "disable the mod, keep the server" possible.
        let errors = [
            ScriptError::Load {
                mod_id: "a".into(),
                detail: String::new(),
            },
            ScriptError::Runtime {
                mod_id: "b".into(),
                context: String::new(),
                detail: String::new(),
            },
            ScriptError::BudgetExceeded {
                mod_id: "c".into(),
                context: String::new(),
            },
            ScriptError::OutOfMemory {
                mod_id: "d".into(),
                context: String::new(),
            },
            ScriptError::RegistrationClosed {
                mod_id: "e".into(),
                what: String::new(),
            },
        ];
        for error in errors {
            assert!(error.mod_id().is_some(), "{error:?} has nobody to blame");
        }

        // A VM failure is the engine's fault, not a mod's.
        assert!(
            ScriptError::Vm {
                backend: "x",
                detail: String::new()
            }
            .mod_id()
            .is_none()
        );
    }

    #[test]
    fn the_instruction_budget_is_per_call_not_per_tick() {
        // Documented as a design decision, asserted so it stays one: a shared
        // budget would make a mod's viability depend on what else is installed.
        let limits = VmLimits::default();
        assert!(limits.instructions_per_call > 0);
        assert!(limits.memory_bytes > 0);
    }
}
