// SPDX-FileCopyrightText: Iridesium
// SPDX-License-Identifier: GPL-3.0-only

//! The backend-agnostic scripting interface.
//!
//! Everything here is deliberately free of any backend's types. If a signature
//! in this file mentions `mlua`, the abstraction has failed.

use std::path::Path;

use crate::chunk::Chunk;
use crate::coords::{BlockPos, ChunkPos, SubNodePos};
use crate::material::MaterialId;

/// Which scripting backend a build was compiled against.
///
/// Reported by `server --version` and written into the world's meta, because a
/// world generated by mods running on one dialect is not guaranteed to
/// regenerate identically on another.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Backend {
    /// Lua 5.4 — the reference implementation. Integer subtype, current
    /// semantics.
    Lua54,
    /// `LuaJIT` — Lua 5.1 semantics, tracing JIT.
    LuaJit,
    /// Luau — Roblox's Lua 5.1 derivative, built for untrusted code.
    Luau,
}

impl Backend {
    /// The dialect mods are written against.
    ///
    /// **This string goes in the modding documentation and cannot change**
    /// without invalidating every mod ever written against it.
    #[must_use]
    pub const fn dialect(self) -> &'static str {
        match self {
            Self::Lua54 => "Lua 5.4",
            Self::LuaJit | Self::Luau => "Lua 5.1",
        }
    }

    /// Whether this backend has an integer subtype.
    ///
    /// The single most mod-visible difference between the candidates. Under
    /// 5.1 semantics every number is a double, so `1/2` is `0.5` and there is
    /// no `//` operator — code written for one dialect misbehaves subtly on the
    /// other rather than failing loudly.
    #[must_use]
    pub const fn has_integers(self) -> bool {
        matches!(self, Self::Lua54)
    }

    /// Whether this backend can bound a runaway loop.
    ///
    /// **`LuaJIT` cannot.** The budget is a debug hook, and `LuaJIT`'s debug hook
    /// does not fire inside JIT-compiled traces — a hot loop compiles, leaves
    /// the interpreter, and never returns to be counted. `while true do end` in
    /// a mod runs forever.
    ///
    /// Charter rule 10 requires a mod error to disable that mod and never kill
    /// the tick, so this is a containment failure rather than a performance
    /// nuance. Recorded here as a property of the backend so it is discoverable
    /// from the code, not only from `docs/scripting-vm.md` §5.
    #[must_use]
    pub const fn can_bound_runaway_loops(self) -> bool {
        !matches!(self, Self::LuaJit)
    }

    /// Whether this backend can enforce a memory ceiling.
    ///
    /// **`LuaJIT` cannot** — its allocator is tied to its own GC and `mlua`
    /// cannot install a limit.
    #[must_use]
    pub const fn can_bound_memory(self) -> bool {
        !matches!(self, Self::LuaJit)
    }

    /// Whether this backend can contain untrusted third-party mods.
    ///
    /// Both containment primitives are required. A backend missing either one
    /// may be built for benchmarking but must not be the shipped default.
    #[must_use]
    pub const fn can_contain_untrusted_mods(self) -> bool {
        self.can_bound_runaway_loops() && self.can_bound_memory()
    }

    /// Short name for logs and documentation.
    #[must_use]
    pub const fn name(self) -> &'static str {
        match self {
            Self::Lua54 => "lua54",
            Self::LuaJit => "luajit",
            Self::Luau => "luau",
        }
    }
}

/// Resource limits applied to a script VM.
///
/// Both limits exist for the same reason: charter rule 10 requires a mod error
/// to disable that mod, never to kill the tick. A mod that loops forever or
/// allocates forever is a mod error, not a server outage.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct VmLimits {
    /// Ceiling on total VM allocation, in bytes.
    pub memory_bytes: usize,
    /// Ceiling on VM instructions executed inside one callback invocation.
    ///
    /// Per *invocation*, not per tick: a budget shared across a tick would make
    /// one mod's cost depend on how many other mods ran first, and a mod that
    /// worked alone would fail once a server installed something else.
    pub instructions_per_call: u32,
}

impl Default for VmLimits {
    fn default() -> Self {
        Self {
            // Generous: a mod holding a large lookup table is legitimate. This
            // is a runaway guard, not a diet.
            memory_bytes: 256 * 1024 * 1024,
            // Roughly a few milliseconds of interpreted Lua. Enough for real
            // orchestration, far short of a tick.
            instructions_per_call: 20_000_000,
        }
    }
}

/// Something went wrong in, or around, a script.
#[derive(Debug, thiserror::Error)]
pub enum ScriptError {
    /// The VM itself could not be created or configured.
    #[error("could not initialise the {backend} script VM")]
    Vm {
        /// Which backend.
        backend: &'static str,
        /// Underlying detail.
        detail: String,
    },

    /// A script failed to load or parse.
    #[error("mod `{mod_id}` failed to load")]
    Load {
        /// Which mod.
        mod_id: String,
        /// The backend's message, including a traceback where available.
        detail: String,
    },

    /// A script raised an error while running.
    ///
    /// Carries the mod id so the tick loop can attribute the fault and disable
    /// that mod without unwinding (charter rule 10).
    #[error("mod `{mod_id}` errored in {context}")]
    Runtime {
        /// Which mod.
        mod_id: String,
        /// What it was doing — the callback name, usually.
        context: String,
        /// The backend's message, including a traceback where available.
        detail: String,
    },

    /// A callback exceeded its instruction budget.
    #[error("mod `{mod_id}` exceeded its instruction budget in {context}")]
    BudgetExceeded {
        /// Which mod.
        mod_id: String,
        /// What it was doing.
        context: String,
    },

    /// A callback exceeded the VM memory limit.
    #[error("mod `{mod_id}` exceeded the script memory limit in {context}")]
    OutOfMemory {
        /// Which mod.
        mod_id: String,
        /// What it was doing.
        context: String,
    },

    /// A script tried to register something after the window closed.
    #[error("mod `{mod_id}` tried to register `{what}` after registration closed")]
    RegistrationClosed {
        /// Which mod.
        mod_id: String,
        /// What it tried to register.
        what: String,
    },
}

impl ScriptError {
    /// The mod to blame, if any.
    ///
    /// Every runtime failure has one, which is what makes "disable the mod, keep
    /// the server" possible.
    #[must_use]
    pub fn mod_id(&self) -> Option<&str> {
        match self {
            Self::Vm { .. } => None,
            Self::Load { mod_id, .. }
            | Self::Runtime { mod_id, .. }
            | Self::BudgetExceeded { mod_id, .. }
            | Self::OutOfMemory { mod_id, .. }
            | Self::RegistrationClosed { mod_id, .. } => Some(mod_id),
        }
    }
}

/// A texture a mod registered for one of its blocks.
///
/// The path is **relative to the mod's own directory** and stays that way all
/// the way to the content index. Resolving it against the filesystem here would
/// mean the engine handing a mod-supplied string to `std::fs`, which is exactly
/// the shape of a path-traversal bug; instead it is a key looked up in an index
/// built by walking that directory, so a path outside it simply does not match.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub struct BlockTexture {
    /// The qualified block id, e.g. `"core:white"`.
    pub block: String,
    /// The mod that registered it, which is also the directory the path is
    /// relative to.
    pub mod_id: String,
    /// Mod-relative path, forward-slashed.
    pub path: String,
}

pub use crate::dig::Brush;

/// What a mod said about how hard a block is to break, and what it yields.
///
/// Held apart from [`BlockTexture`] and [`ScriptVm::registered_blocks`] for the
/// same reason those are apart from each other: the id order is a contract with
/// the material registry, and widening that tuple would drag simulation rules
/// into it.
#[derive(Debug, Clone, PartialEq)]
pub struct BlockRules {
    /// The qualified block id.
    pub block: String,
    /// Seconds to break with a bare hand.
    ///
    /// A default rather than an absence: every block has *some* hardness, and
    /// a mod that omits it gets [`BlockRules::DEFAULT_HARDNESS`] rather than an
    /// unbreakable block, because "I forgot to set hardness" should not produce
    /// bedrock.
    pub hardness: f32,
    /// What breaking it yields, if the mod overrode the default.
    ///
    /// `None` means the ordinary rule from the Sub-Node Contract §9: the block
    /// drops itself, 27 units for a full block and one per occupied cell
    /// otherwise. `Some` replaces that outright, in units.
    pub drops: Option<Vec<(String, u32)>>,
}

impl BlockRules {
    /// Seconds to break a block whose mod said nothing about hardness.
    pub const DEFAULT_HARDNESS: f32 = 0.75;
}

/// A tool a mod registered.
#[derive(Debug, Clone, PartialEq)]
pub struct Tool {
    /// The qualified tool id, e.g. `"core_tools:chisel"`.
    pub id: String,
    /// What to call it on screen, if the mod said.
    ///
    /// `None` falls back to the id, which is always present and always
    /// unambiguous — an unnamed tool should look unpolished, not invisible.
    pub name: Option<String>,
    /// What shape it removes.
    pub brush: Brush,
    /// How much faster than a bare hand it digs.
    pub speed_multiplier: f32,
    /// Whether this is what a player digs with holding nothing.
    ///
    /// The engine has no bare hand of its own. It knows how to *count* a dig
    /// and nothing about what breaking things should feel like, so a world
    /// whose mods register no tools is a world nobody can dig in — which is
    /// the shape charter rule 1 asks for, and is verified by deleting `game/`
    /// in a test.
    ///
    /// Several mods may each mark one; the lowest id wins, so the result does
    /// not depend on load order.
    pub default: bool,
}

/// A dig the server is about to carry out.
///
/// Handed to `on_dig_complete` *before* the geometry goes, so a mod that
/// refuses it leaves the world untouched. Refusing after the fact would mean
/// putting the block back, and putting a block back is not the same as never
/// having removed it — the drops have already been computed and the removal has
/// already been broadcast.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DigEvent {
    /// Who is digging, as the canonical player UUID (charter rule 13 — never
    /// the display name). 32 bytes, because it is a BLAKE3 of the root key.
    pub player: [u8; 32],
    /// The cell under their crosshair.
    pub target: SubNodePos,
    /// What is there.
    pub material: MaterialId,
    /// What the tool would remove.
    pub brush: Brush,
}

/// A placement the server is about to carry out.
///
/// Handed to `on_place` after the engine's own rules have passed — the player
/// holds the material, the target is empty, nobody is standing in it — and
/// before anything is written or charged. A mod refusing here costs the player
/// nothing.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PlaceEvent {
    /// Who is placing.
    pub player: [u8; 32],
    /// The block that would be written.
    pub block: BlockPos,
    /// What it would be made of.
    pub material: MaterialId,
    /// Which of its 27 cells would be filled.
    pub occupancy: u32,
    /// How many units it would cost, which is `occupancy.count_ones()`.
    pub units: u32,
}

/// One entity hitting another.
///
/// **Nothing dispatches this yet, and that is not an oversight.** Entities are
/// Task 12; the only things in the world today are players and voxels, and
/// "left-click on an entity" has nothing to land on. What exists now is the
/// registration and the dispatch path, tested, so that Task 12 adds a caller
/// rather than an API — the same arrangement `register_action` has, which is
/// stored now and inert until Task 13.
///
/// Both parties are canonical UUIDs (charter rule 13). When entities arrive
/// they will need a wider target type than a player UUID, and that is a
/// deliberate future edit rather than something to guess at now.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PunchEvent {
    /// Who threw the punch.
    pub attacker: [u8; 32],
    /// Who received it.
    pub target: [u8; 32],
}

/// What a round of cancellable hooks decided.
///
/// # A faulted mod does not get a veto
///
/// Charter rule 10 says a mod error disables that mod and never kills the tick.
/// The corollary here is that an error is **not** a refusal: a mod that throws
/// while deciding whether a dig may proceed is disabled and the dig goes ahead.
/// The alternative — treating a crash as "no" — would let one broken mod stop
/// everybody on the server from digging, which is a far worse failure than the
/// one it was trying to prevent.
#[derive(Debug, Default)]
pub struct HookOutcome {
    /// Whether the action may proceed.
    pub allowed: bool,
    /// Mods that faulted during this round, now disabled.
    pub faults: Vec<(String, ScriptError)>,
}

impl HookOutcome {
    /// An outcome nothing objected to.
    #[must_use]
    pub const fn allow() -> Self {
        Self {
            allowed: true,
            faults: Vec::new(),
        }
    }
}

/// A script VM hosting the server-mod tier.
///
/// Implementors own the sandbox. Nothing above this trait may assume a
/// particular language, let alone a particular implementation of one.
pub trait ScriptVm: Sized {
    /// Which backend this is.
    fn backend() -> Backend;

    /// Creates a VM with the given limits, with the registration window **open**.
    ///
    /// # Errors
    ///
    /// [`ScriptError::Vm`] if the VM cannot be created or the sandbox cannot be
    /// installed.
    fn create(limits: VmLimits) -> Result<Self, ScriptError>;

    /// Loads a mod's entry chunk into a fresh sandboxed environment.
    ///
    /// `dir` bounds what the mod's `require` can reach. Runs during the
    /// registration window.
    ///
    /// # Errors
    ///
    /// [`ScriptError::Load`] or [`ScriptError::Runtime`] if the chunk fails to
    /// compile or errors while running.
    fn load_mod(&mut self, mod_id: &str, source: &str, dir: &Path) -> Result<(), ScriptError>;

    /// Closes the registration window and freezes the registries.
    ///
    /// Charter rule 9's lifecycle: after this, `register_*` is a hard error.
    ///
    /// # Errors
    ///
    /// [`ScriptError::Vm`] if the VM state cannot be updated.
    fn freeze(&mut self) -> Result<(), ScriptError>;

    /// Whether the registration window has been closed.
    fn is_frozen(&self) -> bool;

    /// Runs every registered `on_generate` callback for one chunk.
    ///
    /// # Errors
    ///
    /// [`ScriptError`] naming the mod that failed. A failure here disables that
    /// mod; it does not stop generation for the others.
    fn generate_chunk(
        &mut self,
        world_seed: u64,
        pos: ChunkPos,
        fill: MaterialId,
    ) -> Result<Chunk, ScriptError>;

    /// Runs every registered `on_tick` callback once.
    ///
    /// `dt_ticks` is how many simulation steps this call covers — normally 1,
    /// but more when the server has fallen behind and is catching up. Mods get
    /// a count of steps rather than a duration on purpose: a duration would
    /// tempt a mod to scale behaviour by wall-clock time, and two servers
    /// running at different speeds would then produce different worlds.
    ///
    /// **A failing mod is disabled, not fatal** (charter rule 10). This runs
    /// every non-faulted mod even if an earlier one errored, and reports the
    /// failures afterwards, because stopping at the first would let one bad mod
    /// silently starve every mod registered after it.
    ///
    /// # Errors
    ///
    /// Never returns `Err` for a mod fault — those are in the returned list.
    /// The `Result` is for a VM-level failure that affects everything.
    fn tick(&mut self, dt_ticks: u32) -> Result<Vec<(String, ScriptError)>, ScriptError>;

    /// Asks every registered `on_dig_complete` whether a dig may proceed.
    ///
    /// Called **before** the geometry is removed. A mod returning `false`
    /// cancels it; returning nothing, `nil`, or anything else allows it, so a
    /// hook that only wants to observe does not have to remember to return
    /// anything.
    ///
    /// **Stops at the first refusal.** Once a dig is not happening, running the
    /// remaining hooks would invite them to take side effects — spawn an
    /// effect, charge something, log a break — for an action that will not
    /// occur. The cost is that a later mod does not observe an attempt an
    /// earlier one vetoed, which is the lesser problem and is deterministic:
    /// hook order is load order, which the resolver already fixed.
    fn dig_complete(&mut self, event: &DigEvent) -> HookOutcome;

    /// Asks every registered `on_place` whether a placement may proceed.
    ///
    /// The same rules as [`Self::dig_complete`], and called after the engine's
    /// own checks pass but before anything is written or charged.
    fn place(&mut self, event: &PlaceEvent) -> HookOutcome;

    /// Asks every registered `on_punch` whether a hit lands.
    ///
    /// The same rules again. **No caller yet** — see [`PunchEvent`]: entities
    /// are Task 12, so there is nothing to punch. This is here, and tested, so
    /// that task adds a caller rather than an API.
    fn punch(&mut self, event: &PunchEvent) -> HookOutcome;

    /// Blocks registered during the loading window, **ordered by numeric id**.
    ///
    /// The order is the contract, not a convenience. The host replays these
    /// into [`crate::material::Registry`], which assigns ids sequentially, so
    /// replaying them in any other order would give a block a different id than
    /// the one the VM handed its mod — and every block that mod placed would
    /// silently be the wrong material.
    fn registered_blocks(&self) -> Vec<(String, MaterialId)>;

    /// Textures registered alongside blocks, ordered by block id.
    ///
    /// Separate from [`Self::registered_blocks`] on purpose: that method's
    /// order is a hard contract with the material registry, and widening its
    /// tuple would put a presentation concern in the middle of it. A block with
    /// no texture simply has no entry here — the engine has no opinion about
    /// what an untextured block looks like, and the client's placeholder is the
    /// client's business.
    fn registered_block_textures(&self) -> Vec<BlockTexture>;

    /// Breaking rules registered alongside blocks, ordered by block id.
    ///
    /// Every registered block appears, including those whose mod said nothing:
    /// the defaults are the engine's answer, and making a caller distinguish
    /// "no entry" from "default entry" is how one of them ends up unbreakable.
    fn registered_block_rules(&self) -> Vec<BlockRules>;

    /// Tools registered during the loading window, ordered by id.
    fn registered_tools(&self) -> Vec<Tool>;

    /// Calls a named zero-argument global, for benchmarking and tests.
    ///
    /// # Errors
    ///
    /// [`ScriptError::Runtime`] if the call fails.
    fn call_void(&mut self, mod_id: &str, name: &str) -> Result<(), ScriptError>;

    /// Evaluates a chunk of source in a mod's environment and returns whether
    /// it succeeded. Test and diagnostic use.
    ///
    /// # Errors
    ///
    /// [`ScriptError`] if the source fails to compile or errors.
    fn eval_in(&mut self, mod_id: &str, source: &str) -> Result<(), ScriptError>;

    /// Mods currently marked faulted, in a stable order.
    ///
    /// A faulted mod's callbacks are skipped. Charter rule 10: a mod error
    /// disables that mod, never the tick.
    fn faulted_mods(&self) -> Vec<String>;

    /// Marks a mod faulted.
    fn mark_faulted(&mut self, mod_id: &str);
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_dialect_string_is_backend_specific() {
        // This string ends up in the modding docs. If it ever changes, every
        // mod written against the old one is at risk.
        assert_eq!(Backend::Lua54.dialect(), "Lua 5.4");
        assert_eq!(Backend::LuaJit.dialect(), "Lua 5.1");
        assert_eq!(Backend::Luau.dialect(), "Lua 5.1");
    }

    #[test]
    fn only_lua54_has_an_integer_subtype() {
        // The most mod-visible difference: under 5.1, `1/2` is 0.5 and there is
        // no `//`. Code silently misbehaves rather than failing loudly.
        assert!(Backend::Lua54.has_integers());
        assert!(!Backend::LuaJit.has_integers());
        assert!(!Backend::Luau.has_integers());
    }

    #[test]
    fn luajit_cannot_contain_untrusted_mods() {
        // Measured, not assumed: the sandbox suite hangs under vm-luajit
        // because the instruction budget never fires inside a compiled trace.
        // See docs/scripting-vm.md §5.
        assert!(!Backend::LuaJit.can_bound_runaway_loops());
        assert!(!Backend::LuaJit.can_bound_memory());
        assert!(!Backend::LuaJit.can_contain_untrusted_mods());

        // The two that can.
        for backend in [Backend::Lua54, Backend::Luau] {
            assert!(
                backend.can_contain_untrusted_mods(),
                "{backend:?} should be able to contain untrusted mods"
            );
        }
    }

    #[test]
    fn every_runtime_error_names_a_mod_to_blame() {
        // What makes "disable the mod, keep the server" possible.
        let errors = [
            ScriptError::Load {
                mod_id: "a".into(),
                detail: String::new(),
            },
            ScriptError::Runtime {
                mod_id: "b".into(),
                context: String::new(),
                detail: String::new(),
            },
            ScriptError::BudgetExceeded {
                mod_id: "c".into(),
                context: String::new(),
            },
            ScriptError::OutOfMemory {
                mod_id: "d".into(),
                context: String::new(),
            },
            ScriptError::RegistrationClosed {
                mod_id: "e".into(),
                what: String::new(),
            },
        ];
        for error in errors {
            assert!(error.mod_id().is_some(), "{error:?} has nobody to blame");
        }

        // A VM failure is the engine's fault, not a mod's.
        assert!(
            ScriptError::Vm {
                backend: "x",
                detail: String::new()
            }
            .mod_id()
            .is_none()
        );
    }

    #[test]
    fn the_instruction_budget_is_per_call_not_per_tick() {
        // Documented as a design decision, asserted so it stays one: a shared
        // budget would make a mod's viability depend on what else is installed.
        let limits = VmLimits::default();
        assert!(limits.instructions_per_call > 0);
        assert!(limits.memory_bytes > 0);
    }
}
